config/routes.rb
Rails.application.routes.draw do
  get 'foodbanks/index'
  get 'foodbanks/show'
  get 'foodbanks/new'
  get 'foodbanks/create'
  get 'foodbanks/edit'
  get 'foodbanks/update'
  get 'foodbanks/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
    resources :recipe_ingredients, only: [:new, :create, :destroy]
    get "recipe_ingredients", to: "recipe_ingredients#recipe_ingredient_list"

  end
  post "recipes/:id/add_favorite", to: "recipes#add_favorite", as: :add_favorite
  post "recipes/:id/remove_favorite", to: "recipes#remove_favorite", as: :remove_favorite
  resources :ingredients, only: [:create, :new]
  resources :users, only: [:show, :update, :edit]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :recipes do
    resources :reviews , only: [:create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true, reject_if: :all_blank
  # accepts_nested_attributes_for :ingredients
  has_many :reviews, dependent: :destroy
  CUISINES = [
    "british",
    "chinese",
    "french",
    "indian",
    "italian",
    "japanese",
    "mexican",
    "spanish",
    "thai"
  ]

  validates :title, presence: true, uniqueness: true, length: {minimum: 4, too_short: "%{count} characters is too short", maximum: 250, too_long: "%{count} characters is the maximum allowed" }
  acts_as_favoritable

  include PgSearch::Model
  pg_search_scope :searching,
    associated_against: {
      ingredients: :name
    },
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }


  def get_rating
    return 0 if self.reviews.empty?
    reviews = self.reviews
    ratings_array = reviews.map { |review| review.rating  }
    return ratings_array.sum / ratings_array.length
  end
#   validates :description, presence: true, length: {minimum: 4, too_short: "%{count} characters is too short", maximum: 150, too_long: "%{count} characters is the maximum allowed" }
#   validates :method, presence: true, length: {minimum: 4, too_short: "%{count} characters is too short", maximum: 10000, too_long: "%{count} characters is the maximum allowed" }
#   validates :level, presence: true, inclusion: { in: %w(Easy Medium Hard), message: "%{value} is not a valid level" }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
    @recipes = @recipes.order(updated_at: :desc)
    @recipe_ingredients = RecipeIngredient.all

    if params[:query].present?
      @recipes = @recipes.searching(params[:query]) if params[:query] != 'true' && params[:ingredient1].nil?
      if !params[:ingredient1].nil?
        if params[:ingredient1] != 'null'
          @recipes = @recipes.searching(params[:ingredient1])
          @recipes = @recipes.order(updated_at: :desc)
        end
        if params[:ingredient2] != 'null'
          @recipes = @recipes.searching(params[:ingredient2])
          @recipes = @recipes.order(updated_at: :desc)
        end
        # if params[:query] != 'true'
        #   # @recipes = @recipes.searching(params[:query])
        # end

        if params[:gluten_free] == 'true'
          @recipes = @recipes.select { |recipe| recipe.gluten_free == true }
        end

        if params[:dairy_free] == 'true'
          @recipes = @recipes.select { |recipe| recipe.dairy_free == true }
        end

        if params[:nut_free] == 'true'
          @recipes = @recipes.select { |recipe| recipe.nut_free == true }
        end

        if params[:egg_free] == 'true'
          @recipes = @recipes.select { |recipe| recipe.egg_free == true }
        end

        if params[:vegetarian] == 'true'
          @recipes = @recipes.select { |recipe| recipe.vegetarian == true }
        end

        if params[:vegan] == 'true'
          @recipes = @recipes.select { |recipe| recipe.vegan == true }
        end


        if params[:easy] == 'true'
          @recipes = @recipes.select { |recipe| recipe.level == "easy" }
        end
        if params[:medium] == 'true'
          @recipes = @recipes.select { |recipe| recipe.level == "medium" }
        end
        if params[:hard] == 'true'
          @recipes = @recipes.select { |recipe| recipe.level == "hard" }
        end


        if params[:british] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "british" }
        end
        if params[:chinese] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "chinese" }
        end
        if params[:french] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "french" }
        end
        if params[:indian] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "indian" }
        end
        if params[:italian] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "italian" }
        end
        if params[:japanese] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "japanese" }
        end
        if params[:mexican] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "mexican" }
        end
        if params[:spanish] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "spanish" }
        end
        if params[:thai] == 'true'
          @recipes = @recipes.select { |recipe| recipe.cuisine == "thai" }
        end
      end
    end


    respond_to do |format|
      format.html
      format.text { render partial: "shared/cardrecipe", locals: { recipes: @recipes }, formats: [:html]}
    end
  end

  def show
    @recipes = Recipe.all
    @recipe = Recipe.find(params[:id])
    @review = Review.new
    @recipe_ingredient = RecipeIngredient.new
  end

  def new
    @recipe = Recipe.new
    # @recipe.recipe_ingredients.build
    @recipe_ingredients = @recipe.recipe_ingredients.build
    # 10.times {@recipe.recipe_ingredients.build}
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save!
      redirect_to recipe_path(@recipe), notice: "Recipe was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])

    @recipe_ingredient = RecipeIngredient.new
    # @ingredients = Ingredient.all

  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: "Recipe was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: "Recipe was successfully deleted"
  end

  def add_favorite
    @recipe = Recipe.find(params[:id])
    current_user.favorite(@recipe)
    redirect_to recipe_path(@recipe)
  end

  def remove_favorite
    @recipe = Recipe.find(params[:id])
    current_user.unfavorite(@recipe)
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :photo, :description, :method, :prep_time, :cook_time, :servings, :cuisine, :level, :vegetarian, :vegan, :dairy_free, :nut_free, :gluten_free, :egg_free, recipe_ingredients_attributes: [:id, :amount, :measurement_type, :ingredient_name])
  end
end

app/views/recipes/_do_not_use.html.erb
<!-- the original code for the ingredients in recipe#new -->
<ul class="content" data-ingredients-target="ingredientsWrapper">
        <template data-ingredients-target="template">
          <%= form.simple_fields_for :recipe_ingredients do |ingredient_form| %>
            <li data-ingredients-target="ingredient" data-id="<%= ingredient_form.options[:child_index] %>">
              <%= ingredient_form.association :ingredient, as: :select, collection: Ingredient.all, input_html: {data: {controller: "tom-select", action: "change->ingredients#add"}} %>
            </li>
          <% end %>
        </template>
        <button type='button'
                class=''
                data-action='click->ingredients#add'>
          Add Ingredient
        </button>
        </ul>

<!-- the original code for the recipe options in recipe#new -->
          <p><i class="fa-solid fa-stopwatch" style="color: #2dd99c;"></i> <%= form.input :prep_time, as: :select, collection: (0..120).step(5), prompt: "minutes", input_html: { class: "form-validation" }  %></p>
          <p><i class="fa-solid fa-fire-burner" style="color: #2dd99c;"></i> <%= form.input :cook_time, as: :select, collection: (0..120).step(5), prompt: "minutes", input_html: { class: "form-validation" } %></p>
          <p><i class="fa-solid fa-traffic-light" style="color: #2dd99c;"></i> <%= form.input :level, as: :select, collection: ["Easy","Medium", "Hard"], input_html: { class: "form-validation" } %></p>
          <p><i class="fa-solid fa-utensils" style="color: #2dd99c;"></i> <%= form.input :servings, as: :select, collection: (1..10), prompt: "servings", input_html: { class: "form-validation" } %></p>

app/views/recipes/edit.html.erb
<div class="container">

  <%= simple_form_for @recipe, html: {data: {controller: "ingredients"}} do |form| %>
      <div class="d-flex justify-content-between">
      <a href="<%=recipes_path%>"><button class="button_default"><i class="fa-solid fa-chevron-left"></i></button></a>
      <%= form.submit "Update recipe", class: "button_default"%>
    </div>

    <div class="d-flex mt-2">

      <div class="imagediv col-6 pe-3">
        <%# <% if recipe.photo %>
        <%= form.input :photo, as: :file %>
        <%# <% end %>
      </div>

      <div class="recipe-info col-6 d-flex flex-column justify-content-between ps-3">
        <div>
          <%= form.input :title %> <br>
          <%= form.input :description %> <br>
        </div>

        <div class="d-flex justify-content-between">
          <div class="d-flex" style="width: 300px">
            <i class="icon-large fa-solid fa-mortar-pestle"></i>
            <div>
              <%= form.input :prep_time, as: :select, collection: (0..120).step(5), prompt: "minutes", input_html: { class: "form-validation" }  %>
            </div>
          </div>
          <div class="d-flex" style="width: 300px">
            <div class="d-flex justify-content-end" style="width: 40px"><i class="icon-large fa-solid fa-stopwatch"></i>
            </div>
            <div>
              <%= form.input :cook_time, as: :select, collection: (0..120).step(5), prompt: "minutes", input_html: { class: "form-validation" } %>
            </div>
          </div>
          <div class="d-flex" style="width: 300px">
            <i class="icon-large fa-solid fa-utensils"></i>
            <div>
              <%= form.input :servings, as: :select, collection: (1..10), prompt: "servings", input_html: { class: "form-validation" } %>
            </div>
          </div>
        </div>

        <div class="d-flex justify-content-between">
          <div class="d-flex" style="width: 300px">
            <i class="icon-large fa-solid fa-earth-americas"></i>
            <div>
              <%= form.input :cuisine, as: :select, collection: Recipe::CUISINES, input_html: { class: "form-validation" } %>
            </div>
          </div>
          <div class="d-flex" style="width: 300px">
            <div class="d-flex justify-content-end" style="width: 40px"><i class="icon-large fa-solid fa-traffic-light"></i>
            </div>
            <div>
              <%= form.input :level, as: :select, collection: ["Easy","Medium", "Hard"], input_html: { class: "form-validation" } %>
            </div>
          </div>
        </div>

          <div class="d-flex">
            <i class="icon-large fa-solid fa-seedling"></i>
            <div class="d-flex flex-column">
              <p>Allergens</p>
              <div class="d-flex justify-content-between">
                <div><%= form.input :vegetarian, as: :boolean, label: 'Vegetarian' %></div>
                <div><%= form.input :vegan, as: :boolean, label: 'Vegan' %></div>
                <div><%= form.input :dairy_free, as: :boolean, label: 'Dairy Free' %></div>
                <div><%= form.input :nut_free, as: :boolean, label: 'Nut Free' %></div>
                <div><%= form.input :gluten_free, as: :boolean, label: 'Gluten Free' %></div>
                <div><%= form.input :egg_free, as: :boolean, label: 'Egg Free' %></div>
              </div>
            </div>
          </div>
      </div>

    </div>

     <div class="bottomhalf d-flex">

    <div class="index_recipecard col-6 pe-4">
      <h2 class="top">Ingredients</h2>
      <ul class="content i" data-ingredients-target="ingredientsWrapper">
        <%= form.simple_fields_for :recipe_ingredients do |recipe_ingredient_form| %>
            <!-- Use the virtual attribute for ingredient name -->
          <li>
            <%= recipe_ingredient_form.input :ingredient_name, placeholder: "Enter ingredient name" %>
            <%= recipe_ingredient_form.input :amount %>
            <%= recipe_ingredient_form.input :measurement_type %>
            <%= recipe_ingredient_form.hidden_field :_destroy %>
            <%= link_to "Remove", '#', class: "remove-recipe-ingredient" %>
          </li>
        <% end %>
    <!-- Button to add a new recipe ingredient -->
        <p class="btn btn-primary" data-action="click->ingredients#add">Add another Ingredient</p>
      </ul>
    </div>

    <div class="col-6">
      <div class="index_recipecard recipe-method">
        <h2 class="top">Method</h2>
        <div class="content m">
          <%= form.input :method, class: "methodbox"%>
        </div>
      </div>
    </div>

    </div>



      <%# <div class="index_recipecard col-6">
        <h2 class="top">Ingredients</h2>
        <ul class="content" data-ingredients-target="ingredientsWrapper">
        <template data-ingredients-target="template">
          <%= form.simple_fields_for :recipe_ingredients, input_html: {class: "form-validation"} do |ingredient_form| %>
            <%# <li data-ingredients-target="ingredient" data-id="<%= ingredient_form.options[:child_index] %>
              <%# <%= ingredient_form.association :ingredient, as: :select, collection: Ingredient.all, input_html: {data: {controller: "tom-select", action: "change->ingredients#add"}}, wrapper_html: {class: "form-validation"} %>
            <%# </li>
          <% end %>
        <%# </template>
        <button type='button'
                class=''
                data-action='click->ingredients#add'>
          Add Ingredient
        </button>
        </ul>
      </div> %>


    </div><%# <p class="btn btn-primary" data-action="click->ingredients#add">Add another Ingredient</p> %>

  <% end %>
</div>

app/views/recipes/index.html.erb
<%# this page is search results and links to the recipe card scss %>

<div data-controller="filtered-index"  >
<%# //class="container" %>
  <div class="wrapper">
    <div class="row" style="width: 100vw;">
      <div class="side_bar col-3" style="overflow-y: scroll;">
          <div class="addcomponenet">
            <h2 class="top"><strong>add. </strong></h2>
            <div class="content" data-filtered-index-target="content">
              <div class= "d-flex">
                <%= render "shared/search_bar_index"%>
              </div>
            </div>
          </div>


            <div class="accordion" id="accordionPanelsStayOpenExample">

              <div class="retractablecontainer">
                <h2 class="accordion-header">
                   <button class="accordion-button top collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                   <i class="fa-solid fa-seedling"></i> Allergens
                  </button>
                </h2>
                <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">
                    <div class="accordion-body content">
                            <%# <label class="container">One
                            <input type="checkbox" checked="checked">
                            <span class="checkmark"></span> %>
                            </label>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="vegetarian">
                            <label class="tick"> Vegetarian</label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="vegan">
                            <label class="tick"> Vegan</label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="gluten_free">
                            <label class="tick"> Gluten Free</label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="dairy_free">
                            <label class="tick"> Dairy Free</label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="egg_free">
                            <label class="tick"> Egg Free</label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="nut_free">
                            <label class="tick"> Nut Free</label><br>

                  </div>
                </div>
              </div>

              <div class="retractablecontainer">
                <h2 class="accordion-header">
                  <button class="accordion-button top collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                    <i class="fa-solid fa-bowl-food"></i> Cuisine

                  </button>
                </h2>
                <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
                  <div class="accordion-body content">
                          <%# TODO - ADD ALLERGENS %>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="british">
                            <label class="tick"> British</label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="chinese">
                            <label class="tick"> Chinese</i></label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="french">
                            <label class="tick"> French</i></label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="indian">
                            <label class="tick"> Indian </i></label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="italian">
                            <label class="tick"> Italian </i></label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="japanese">
                            <label class="tick"> Japanese </i></label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="mexican">
                            <label class="tick"> Mexican </i></label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="spanish">
                            <label class="tick"> Spanish </i></label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="thai">
                            <label class="tick"> Thai </i></label><br>
                  </div>
                </div>
              </div>


              <div class="retractablecontainer">
                <h2 class="accordion-header">
                  <button class="accordion-button top collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                    <i class="fa-solid fa-traffic-light"></i>Difficulty

                  </button>
                </h2>
                <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
                  <div class="accordion-body content">
                          <%# TODO - ADD ALLERGENS %>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="easy">
                            <label class="tick"> Easy </label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="medium">
                            <label class="tick"> Medium</i></label><br>
                            <input type="checkbox" data-action="click->filtered-index#sendRequest" data-filtered-index-target="checkbox" id="hard">
                            <label class="tick"> Hard</i></label><br>
                  </div>
                </div>
              </div>

            </div>

        </div>
        <div class="col-3"></div>

        <div class="col-9">
          <h1 class="pagetitle">Sustainably Scrumptious Recipes</h1>
          <div class="card-grid" data-filtered-index-target='container'>
            <%= render "shared/cardrecipe", recipes: @recipes %>
          </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-end m-3">
<%= link_to "Back to top", recipes_path, class: "button_default" %>
</div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="justify-content-between d-flex">
    <a href="<%=recipes_path%>"><button class="button_default"><i class="fa-solid fa-chevron-left"></i></button></a>



    <% if current_user == @recipe.user %>
      <a href="<%=edit_recipe_path(@recipe)%>"><button class="button_default"><i class="fa-solid fa-pencil"></i></button></a>
    <% end %>
  </div>
  <div class="d-flex mt-2">

    <div class="imagediv col-6 pe-5">
       <div class="favoriting">
          <% if current_user %>
            <% if current_user.favorited?(@recipe) %>
              <%= link_to remove_favorite_path(@recipe), data: {turbo_method: :post} do%>
                <i class="fa-solid fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to add_favorite_path(@recipe), data: {turbo_method: :post} do%>
                <i class="fa-regular fa-heart"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% if @recipe.photo.attached? %>
        <%= cl_image_tag @recipe.photo.key, class: "recipe-image" %>
      <% elsif @recipe.image_url == nil %>
        <%= image_tag ("logo_small.png"), class: "recipe-image" %>
      <% else %>
        <%= image_tag (@recipe.image_url), class: "recipe-image" %>
      <% end %>
    </div>

    <div class="recipe-info col-6 d-flex flex-column justify-content-between">

      <div class="showtitle">
        <h1><strong><%= @recipe.title %></strong></h1>
        <h5><%= @recipe.description %></h5>
      </div>

      <div>

      <div class="d-flex justify-content-between mt-auto">
        <div class="d-flex align-items-center mb-3">
        <%= link_to user_path(@recipe.user) do%>
          <% if @recipe.user.photo.attached? %>
            <%= cl_image_tag @recipe.user.photo.key, class: "avatar-bordered" %>
          <% elsif @recipe.user.image.empty? %>
            <%= image_tag ("avatar.png"), class: "avatar-bordered" %>
          <% else %>
            <%= image_tag (@recipe.user.image), class: "avatar-bordered" %>
          <% end %>
          <div class="ms-2 d-flex flex-column align-items-start">
            <p><strong><%= @recipe.user.username %></strong></p>
            <%end%>
            <p>June 2023</p>
          </div>
        </div>
        <div class="d-flex flex-column align-items-end">
          <div class="rating-stars d-flex">
            <% @recipe.get_rating.times do %>
              <p><i class="fa-solid fa-star"></i></p>
            <% end %>
            <% (5 - @recipe.get_rating).times do %>
              <p><i class="fa-regular fa-star"></i></p>
            <% end %>
          </div>
          <a href="#reviews"><button class="button_default green special">See Reviews</button></a>
        </div>
      </div>
 </div>

  <div class="infos">
      <div class="d-flex justify-content-between">
        <div class="d-flex" style="width: 300px">
          <i class="icon-large fa-solid fa-mortar-pestle"></i>
          <div>
            <h5>Prep time</h5>
            <p class="allergens_show"><%= @recipe.prep_time.to_i %> minutes</p>
          </div>
        </div>
        <div class="d-flex" style="width: 300px">
            <div class="d-flex justify-content-end" style="width: 40px"><i class="icon-large fa-solid fa-stopwatch"></i></div>
            <div>
              <h5>Cook time</h5>
              <p class="allergens_show"><%= @recipe.cook_time.to_i %> minutes</p>
            </div>
        </div>
        <div class="d-flex" style="width: 300px">
            <i class="icon-large fa-solid fa-utensils"></i>
            <div>
              <h5>Servings</h5>
              <p class="allergens_show"><%= @recipe.servings %></p>
            </div>
        </div>
      </div>

      <div class="d-flex justify-content-between">
        <div class="d-flex" style="width: 300px">
          <i class="icon-large fa-solid fa-earth-americas"></i>
          <div>
            <h5>Cuisine</h5>
            <p class="allergens_show"><%= @recipe.cuisine %></p>
          </div>
        </div>
        <div class="d-flex" style="width: 300px">
            <div class="d-flex justify-content-end" style="width: 40px"><i class="icon-large fa-solid fa-traffic-light"></i></div>
            <div>
              <h5>Difficulty</h5>
              <p class="allergens_show"><%= @recipe.level %></p>
            </div>
        </div>
        <div class="d-flex" style="width: 300px">
            <i class="icon-large fa-solid fa-seedling"></i>
            <div>
              <h5>Allergens</h5>
              <p class="allergens_show">
              <%= "V" if @recipe.vegetarian %>
              <%= "VE" if @recipe.vegan %>
              <%= "GF" if @recipe.gluten_free %>
              <%= "DF" if @recipe.dairy_free %>
              <%= "NF" if @recipe.nut_free %>
              <%= "EF" if @recipe.egg_free %>
              </p>
            </div>
        </div>
      </div>
    </div>
    </div>
  </div>

  <div class="bottomhalf d-flex">


    <div class="index_recipecard col-6">
      <h2 class="top">Ingredients</h2>
      <ul class="content i" >
        <% @recipe.recipe_ingredients.each do |ingredient| %>
          <li><input type="checkbox" class="steps">
          <%= ingredient.amount %>
          <%= ingredient.measurement_type %>
          <label> <%= ingredient.ingredient.name.capitalize %></label><br></li>
        <% end %>
      </ul>
    </div>

    <div class="col-6">
      <div class="index_recipecard recipe-method">
        <h2 class="top">Method</h2>
        <div class="content m" style="overflow-y: scroll;">
          <p><%= simple_format(@recipe.method) %></p>
        </div>
      </div>
    </div>



  </div>

  <div class="random-recipe-cards mt-4">
    <h2>More recipes from your <strong>frydg.</strong></h2>
    <div class="d-flex mb-5" style="overflow-x: auto;">
      <% @recipes = @recipes.where.not(id: @recipe.id).sample(5) %>
      <%= render "shared/cardrecipe", recipes: @recipes %>
    </div>
  </div>

  <div class="index_recipecard"  id="reviews">
    <h1 class="top">Reviews</h1>
    <div class="content" data-controller="insert-reviews">

      <div class="reviewsection mt-5">
        <%= render 'reviews/form', recipe: @recipe, review: @review%>
      </div>

      <div class="review-container" data-insert-reviews-target="list">

        <%# <ul class="list-group"> %>
        <% @recipe.reviews.each do |review| %>
          <%= render 'reviews/review', review: review %>
        <% end %>
      </div>



    </div>
  </div>

</div>