config/routes.rb
Rails.application.routes.draw do
  get 'foodbanks/index'
  get 'foodbanks/show'
  get 'foodbanks/new'
  get 'foodbanks/create'
  get 'foodbanks/edit'
  get 'foodbanks/update'
  get 'foodbanks/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
    resources :recipe_ingredients, only: [:new, :create, :destroy]
    get "recipe_ingredients", to: "recipe_ingredients#recipe_ingredient_list"

  end
  post "recipes/:id/add_favorite", to: "recipes#add_favorite", as: :add_favorite
  post "recipes/:id/remove_favorite", to: "recipes#remove_favorite", as: :remove_favorite
  resources :ingredients, only: [:create, :new]
  resources :users, only: [:show, :update, :edit]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :recipes do
    resources :reviews , only: [:create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_bio.html.erb
  <div class=" profile-bio">
    <h2>Bio</h2>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldu</p>
  </div>

app/views/shared/_buttons.html.erb
<%# TODO - what are the buttons we need? (Replace with logos later) %>
<%# styling = white with green %>
  <%# see reviews %>
  <a href="#"><button class="button_default special">See Reviews</button></a>
  <%# add reviews %>
  <a href="#"><button class="button_default">Add Review +</button></a>
  <%# add recipes + %>
  <a href="#"><button class="button_default">Add Recipe +</button></a>
  <%# log out  %>
  <a href="#"><button class="button_default">Log Out</button></a>
  <%# see more %>
  <a href="#"><button class="button_default">See More</button></a>
  <%# < Back  %>
  <a href="#"><button class="button_default">Back</button></a>
  <%# edit (after first one) %>
  <a href="#"><button class="button_default">Edit</button></a>
  <%# save %>
  <a href="#"><button class="button_default">Save</button></a>
  <%# + (steps) %>
  <a href="#"><button class="button_default round"><i class="fa-solid fa-plus"></i></button></a>
  <%# go-o (for sign in) %>
  <a href="#"><button class="button_default">GO <i class="fa-regular fa-circle-right"></i></button></a>
<%# styling = green with white %>
  <%# GO -O %>
  <a href="#"><button class="button_default green">GO <i class="fa-regular fa-circle-right"></i></button></a>
  <%# edit (first one) %>
  <a href="#"><button class="button_default green">Edit</button></a>
  <%# done  %>
  <a href="#"><button class="button_default green">Done</button></a>
  <%# + (ingredients) %>
   <a href="#"><button class="button_default green round"><i class="fa-solid fa-plus"></i></button></a>
<%# styling = other %>
  <%# <3 %>
  <%# bin %>
  <%# sign in to open your fridge %>

app/views/shared/_cardfavourite.html.erb
<div class="card-product">
  <%if recipe.photo.attached? %>
    <li class="text-decoration"><%= cl_image_tag recipe.photo.key %></li>
  <% else %>
    <li class="text-decoration"><%= image_tag recipe.image_url %></li>
  <% end %>
  <div class="card-product-infos">
<li class="text-decoration"><strong><%= recipe.title %></strong></li>
  <div class="allergens d-flex">
          <% if recipe.vegetarian %>
            <li>V</li>
          <% end %>
          <% if recipe.vegan %>
            <li>Ve</li>
          <% end %>
          <% if recipe.dairy_free %>
            <li>DF</li>
          <% end %>
          <% if recipe.gluten_free %>
            <li>GF</li>
          <% end %>
          </div>
   </div>
</div>

app/views/shared/_cardrecipe.html.erb
<% @recipes.each do |recipe| %>
  <div class="styling">
    <%= link_to recipe_path(recipe) do %>

    <ul class="card_recipes_defaultv">
      <% if recipe.photo.attached? %>
        <%= cl_image_tag recipe.photo.key, class: "recipecards_img" %>
      <% elsif recipe.image_url != nil %>
        <%= image_tag (recipe.image_url), class: "recipecards_img" %>
      <% else %>
        <%= image_tag ("logo_small.png"), class: "recipecards_img" %>
      <% end %>

      <div class="favoriting_index">
        <% if current_user %>
          <% if current_user.favorited?(recipe) %>
            <%= link_to remove_favorite_path(recipe), data: {turbo_method: :post} do%>
              <i class="fa-solid fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to add_favorite_path(recipe), data: {turbo_method: :post} do%>
              <i class="fa-regular fa-heart"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="bottomcontainer">
        <li class="recipe_card_title"><strong><%= recipe.title %></strong></li>
        <div class="allergens d-flex">
          <% if recipe.vegetarian %>
            <li>V</li>
          <% end %>
          <% if recipe.vegan %>
            <li>Ve</li>
          <% end %>
          <% if recipe.dairy_free %>
            <li>DF</li>
          <% end %>
          <% if recipe.gluten_free %>
            <li>GF</li>
          <% end %>
          <% if recipe.nut_free %>
            <li>NF</li>
          <% end %>
          <% if recipe.egg_free %>
            <li>EF</li>
          <% end %>
        </div>
        <%# took out cuisine more useful as search tool %>
        <div class="infograms d-flex">
          <li><i class="fa-solid fa-mortar-pestle"></i> <%= recipe.prep_time.to_i %> mins</li>
          <li><i class="fa-solid fa-stopwatch"></i> <%= recipe.cook_time.to_i %> mins</li>
          <li><i class="fa-solid fa-traffic-light"></i> <%= recipe.level %></li>
        </div>
      </div>
    </ul>
    <% end %>
  </div>
<% end %>

app/views/shared/_favourites.html.erb
<div class=" profile-favourites">
  <h2>My Favourite Recipes</h2>
  <div class="card-grid-favourites col-12">
    <% favorites.each do |recipe| %>
      <%= link_to recipe_path(recipe) do %>
        <%= render "shared/cardfavourite", recipe: recipe %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar container-fluid">
  <!-- Logo in the Middle -->
  <div class= "our-logo">
    <%= link_to recipes_path, class: "navbar-brand mx-auto logo" do %>
      <%= image_tag "logo.png", alt: "Your Logo" %>
    <% end %>
  </div>
  <!--- end --->
  <!-- search bar -->
  <%# <%= render "shared/search_bar" %>
  <!--- end --->
  <!-- Profile Sign-in Button on the Right -->
  <div class="navbar-nav">
    <div class="sidebar-nav">
      <i class="burger fa-solid fa-burger fa-2xl" data-bs-toggle="offcanvas" data-bs-target="#sidebar" aria-controls="sidebar" style="color: #ffffff; border: none; background-color: transparent; cursor: pointer;"></i>
    </div>
  </div>
  <!--- end --->
</div>
<div class="spacer mb-3"></div>

app/views/shared/_profile.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <div class="left m-3 col-md-7">
      <div class="profile-info">
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class: "avatar-profile" %>
        <% elsif @user.image.empty? %>
          <%= image_tag ("avatar.png"), class: "avatar-profile" %>
        <% else %>
          <%= image_tag (@user.image), class: "avatar-profile" %>
        <% end %>
        <p><%= @user.username %></p>
        <div class="profile-details">
          <h5><%= @user.first_name %> <%= @user.last_name %> | <%= @user.postcode %></h5>
        </div>
        <div class="profile-icons">
          <a href="http://www.instagram.com"><i class="fa-brands fa-instagram" style="color: #cd4cc8;"></i></a>
          <a href="http://www.facebook.com"> <i class="fa-brands fa-facebook" style="color: #30658d;"></i> </a>
        </div>
      </div>
      <div class="profile-recipes">
        <h2>My Recipes</h2>
        <%= link_to new_recipe_path, class: "button_default_add" do %>
          <h2>Add Recipe +</h2>
        <% end %>
        <div id="recipeCarousel" class="carousel carousel-dark slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @recipes.each_slice(2).with_index do |slice, index| %>
              <div class="carousel-item <%= 'active' if index.zero? %>">
                <div class="d-flex justify-content-center">
                  <% slice.each do |recipe| %>
                    <%= link_to recipe_path(recipe) do %>
                      <%= render "shared/cardrecipe", recipe: recipe %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#recipeCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#recipeCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
          </button>
        </div>
      </div>
    </div>
     <div class="*right* col-md-5 justify-content-center">
        <%= render "shared/favourites", favorites: @favorite_recipes %>
    </div>
  </div>
</div>

app/views/shared/_search_bar_home.html.erb
<div class="search-containerh">
  <%= form_with url: recipes_path, method: :get, class: "d-flex search-containerh" do %>
    <%= text_field_tag :query ,
          params[:query],
          class: "form-control searchbarh me-2",
          placeholder: "Search",
          data: { filtered_index_target: "search" }
    %>
    <a><button type="submit" class="button_default btn-plus green round" data-action="click->filtered-index#sendRequest"><i class="fa-solid fa-plus"></i></button></a>
  <% end %>
</div>

<style>
  .searchbarh {
    border-radius: 30px;
    border-color: #177152;
    width: 360px;
    height: 60px;
  }
  .search-containerh {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
  }
</style>

app/views/shared/_search_bar_index.html.erb
<div class="search-containeri">
  <%= form_with url: recipes_path, method: :get, class: "d-flex search-containeri" do %>
    <%= text_field_tag :query ,
          params[:query],
          class: "form-control searchbari me-2",
          placeholder: "Search",
          data: { filtered_index_target: "search" }
    %>
    <a><button type="submit" class="button_default btn-plus green round" data-action="click->filtered-index#sendRequest"><i class="fa-solid fa-plus"></i></button></a>
  <% end %>
</div>

<style>
  .searchbari {
    border-radius: 30px;
    width: 190px;
    height: 50px;
    font-size: 18px;
    color: #177152;
  }

  .search-containeri {
    width: 250px;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;

  }
</style>

app/views/shared/_sidebar.html.erb
    <div class="offcanvas-body">
      <div class="sidebar-all">
        <div class="offcanvas offcanvas-end" tabindex="-1" id="sidebar">
          <div class="offcanvas-header">
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <!-- Menu items -->
          <ul class="sidebar-nav">
            <li class="nav-item">
              <h1>Menu</h1>
            </li>
            <li class="nav-item1">
              <%= link_to "All Recipes", recipes_path, class: "nav-link" %>
            </li>
            <li class="nav-item1">
              <%= link_to "Food Bank It", foodbanks_index_path, class: "nav-link" %>
            </li>
            <%if user_signed_in?%>
              <li class="quick-actions">
                <%= link_to "Add Recipe", new_recipe_path, class: "action-link" %>
              </li>
              <li class="user-info">
                <% if current_user.photo.attached? %>
                  <%= cl_image_tag current_user.photo.key, class: "profile-pic" %>
                <% elsif current_user.image.empty? %>
                  <%= image_tag ("avatar.png"), class: "profile-pic" %>
                <% else %>
                  <%= image_tag (current_user.image), class: "profile-pic" %>
                <% end %>
                 </li>
              <a class="user-name" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                <li>
                  <h5 class="user-name dropdown-toggle"><%= current_user.username%></h5>
                </li>
              </a>
              <div class="collapse" id="collapseExample">
                <li class="action-link">
                  <div class="card card-body">
                    <%= link_to "My Profile", user_path(current_user), class: "nav-link" %>
                    <%= link_to "Manage Account", edit_user_registration_path, class: "action-link" %>
                    <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
                  </div>
                </div>
              </li>
            <%else%>
              <li class="nav-item1">
                <%= link_to "Log In", new_user_session_path, class: 'nav-link'%>
              </li>
            <% end %>
            <li class="sidebar-footer">
              <p>
                © 2024 Frydg</p>
            </li>
          </ul>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_users_view.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <div class="left m-3 col-md-7">
      <div class="profile-info">
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class: "avatar-profile" %>
        <% elsif @user.image.empty? %>
          <%= image_tag ("avatar.png"), class: "avatar-profile" %>
        <% else %>
          <%= image_tag (@user.image), class: "avatar-profile" %>
        <% end %>
        <p><%= @user.username %></p>
        <div class="profile-details">
          <h5><%= @user.first_name %> <%= @user.last_name %> | <%= @user.postcode %></h5>
        </div>
        <div class="profile-icons">
          <a href="http://www.instagram.com"><i class="fa-brands fa-instagram" style="color: #cd4cc8;"></i></a>
          <a href="http://www.facebook.com"> <i class="fa-brands fa-facebook" style="color: #30658d;"></i> </a>
        </div>
      </div>

      <div class="profile-recipes">
        <h2>Their Recipes</h2>
        <div id="recipeCarousel" class="carousel carousel-dark slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @recipes.each_slice(2).with_index do |s, index| %>
              <div class="carousel-item <%= 'active' if index.zero? %>">
                <div class="d-flex justify-content-center">
                  <% s.each do |recipe| %>
                    <%= link_to recipe_path(recipe) do %>
                      <%= render "shared/cardrecipe", recipe: recipe %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#recipeCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#recipeCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
          </button>
        </div>
      </div>
    </div>

     <div class="*right* col-md-5 justify-content-center">
        <%= render "shared/bio" %>
    </div>
  </div>
</div>